"""initial_schema

Revision ID: 33c15cb91fa6
Revises: 
Create Date: 2026-09-30 12:01:36.395946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c15cb91fa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_table('guardians',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('language', sa.Enum('rw', 'en', 'fr', name='guardian_language_enum'), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_source', sa.Enum('school_form', 'ussd', 'dashboard', name='consent_source_enum'), nullable=True),
    sa.Column('sms_opt_out', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_phone_e164'), 'guardians', ['phone_e164'], unique=True)
    op.create_table('holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.create_table('terms',
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('term_no', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'term_no', name='uq_term_year_no')
    )
    op.create_index(op.f('ix_terms_academic_year'), 'terms', ['academic_year'], unique=False)
    op.create_table('ussd_requests',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('n_inputs', sa.Integer(), nullable=False),
    sa.Column('screen_key', sa.String(length=50), nullable=False),
    sa.Column('response_kind', sa.String(length=10), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'n_inputs')
    )
    op.create_index(op.f('ix_ussd_requests_created_at'), 'ussd_requests', ['created_at'], unique=False)
    op.create_table('sectors',
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_sector_district_name')
    )
    op.create_index(op.f('ix_sectors_district_id'), 'sectors', ['district_id'], unique=False)
    op.create_table('schools',
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Enum('primary', 'secondary', 'both', name='school_level_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'name', name='uq_school_sector_name')
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_index(op.f('ix_schools_sector_id'), 'schools', ['sector_id'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.Enum('admin', 'district_director', 'sector_officer', 'head_teacher', 'teacher', 'mentor', name='user_role_enum'), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_failed_count', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.Enum('rw', 'en', 'fr', name='user_language_enum'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('sector_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_index(op.f('ix_users_sector_id'), 'users', ['sector_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('classes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', 'academic_year', name='uq_class_school_name_year')
    )
    op.create_index(op.f('ix_classes_class_teacher_id'), 'classes', ['class_teacher_id'], unique=False)
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('ussd_sessions',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('authed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_ussd_sessions_phone_hash'), 'ussd_sessions', ['phone_hash'], unique=False)
    op.create_table('attendance_submissions',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('ussd', 'dashboard', name='submission_source_enum'), nullable=False),
    sa.Column('absent_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'date', name='uq_attendance_submission_class_date')
    )
    op.create_index(op.f('ix_attendance_submissions_class_id'), 'attendance_submissions', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_date'), 'attendance_submissions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_submissions_submitted_by'), 'attendance_submissions', ['submitted_by'], unique=False)
    op.create_table('class_teachers',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'user_id')
    )
    op.create_table('students',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('student_code', sa.String(length=50), nullable=True),
    sa.Column('roll_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('sex', sa.Enum('F', 'M', name='student_sex_enum'), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('is_repeater', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'transferred', 'dropped_out', 'graduated', name='student_status_enum'), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'roll_number', name='uq_student_class_roll')
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
    op.create_table('absences',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'voided', name='absence_status_enum'), nullable=False),
    sa.Column('reason_code', sa.Enum('SICK', 'WORK', 'COST', 'DISTANCE', 'OTHER', name='absence_reason_code_enum'), nullable=True),
    sa.Column('reason_source', sa.Enum('parent', 'teacher', 'mentor', name='absence_reason_source_enum'), nullable=True),
    sa.Column('reason_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['attendance_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_absence_student_date')
    )
    op.create_index(op.f('ix_absences_date'), 'absences', ['date'], unique=False)
    op.create_index(op.f('ix_absences_reason_code'), 'absences', ['reason_code'], unique=False)
    op.create_index(op.f('ix_absences_status'), 'absences', ['status'], unique=False)
    op.create_index(op.f('ix_absences_student_id'), 'absences', ['student_id'], unique=False)
    op.create_index(op.f('ix_absences_submission_id'), 'absences', ['submission_id'], unique=False)
    op.create_table('cases',
    sa.Column('ref', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'mentor_assigned', 'visited', 'escalated_sector', 'escalated_district', 'resolved_returned', 'closed_moved', 'closed_other', name='case_status_enum'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('consecutive', 'monthly', 'term_total', 'manual', name='case_trigger_enum'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=True),
    sa.Column('sector_officer_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_mentor_id', 'cases', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_cases_ref'), 'cases', ['ref'], unique=True)
    op.create_index(op.f('ix_cases_school_id'), 'cases', ['school_id'], unique=False)
    op.create_index(op.f('ix_cases_sector_officer_id'), 'cases', ['sector_officer_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index('ix_cases_status_school', 'cases', ['status', 'school_id'], unique=False)
    op.create_index(op.f('ix_cases_student_id'), 'cases', ['student_id'], unique=False)
    op.create_table('help_requests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('barrier_code', sa.Enum('COST', 'HUNGER', 'HEALTH', 'DISTANCE', 'FAMILY', 'OTHER', name='barrier_code_enum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'seen', 'in_progress', 'closed', name='help_request_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_requests_guardian_id'), 'help_requests', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_help_requests_status'), 'help_requests', ['status'], unique=False)
    op.create_index(op.f('ix_help_requests_student_id'), 'help_requests', ['student_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'guardian_id')
    )
    op.create_table('case_events',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('mentor_visits',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_method', sa.Enum('parent_code', 'unverified', name='verified_method_enum'), nullable=False),
    sa.Column('outcome', sa.Enum('will_return', 'plan_agreed', 'needs_sector_help', 'moved_away', name='visit_outcome_enum'), nullable=False),
    sa.Column('barrier_code', sa.Enum('COST', 'HUNGER', 'HEALTH', 'DISTANCE', 'FAMILY', 'OTHER', name='barrier_code_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_visits_case_id'), 'mentor_visits', ['case_id'], unique=False)
    op.create_index(op.f('ix_mentor_visits_mentor_id'), 'mentor_visits', ['mentor_id'], unique=False)
    op.create_table('sms_outbox',
    sa.Column('to_e164', sa.String(length=20), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', 'skipped', name='sms_status_enum'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_student_id', sa.UUID(), nullable=True),
    sa.Column('related_case_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_outbox_dedupe_key'), 'sms_outbox', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_sms_outbox_scheduled_at'), 'sms_outbox', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_sms_outbox_status'), 'sms_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_sms_outbox_to_e164'), 'sms_outbox', ['to_e164'], unique=False)
    op.create_table('visit_codes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_codes_case_id'), 'visit_codes', ['case_id'], unique=False)
    op.create_index(op.f('ix_visit_codes_expires_at'), 'visit_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_visit_codes_mentor_id'), 'visit_codes', ['mentor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_codes_mentor_id'), table_name='visit_codes')
    op.drop_index(op.f('ix_visit_codes_expires_at'), table_name='visit_codes')
    op.drop_index(op.f('ix_visit_codes_case_id'), table_name='visit_codes')
    op.drop_table('visit_codes')
    op.drop_index(op.f('ix_sms_outbox_to_e164'), table_name='sms_outbox')
    op.drop_index(op.f('ix_sms_outbox_status'), table_name='sms_outbox')
    op.drop_index(op.f('ix_sms_outbox_scheduled_at'), table_name='sms_outbox')
    op.drop_index(op.f('ix_sms_outbox_dedupe_key'), table_name='sms_outbox')
    op.drop_table('sms_outbox')
    op.drop_index(op.f('ix_mentor_visits_mentor_id'), table_name='mentor_visits')
    op.drop_index(op.f('ix_mentor_visits_case_id'), table_name='mentor_visits')
    op.drop_table('mentor_visits')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_help_requests_student_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_status'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_guardian_id'), table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index(op.f('ix_cases_student_id'), table_name='cases')
    op.drop_index('ix_cases_status_school', table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_sector_officer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_school_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_ref'), table_name='cases')
    op.drop_index('ix_cases_mentor_id', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_absences_submission_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_student_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_status'), table_name='absences')
    op.drop_index(op.f('ix_absences_reason_code'), table_name='absences')
    op.drop_index(op.f('ix_absences_date'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('class_teachers')
    op.drop_index(op.f('ix_attendance_submissions_submitted_by'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_date'), table_name='attendance_submissions')
    op.drop_index(op.f('ix_attendance_submissions_class_id'), table_name='attendance_submissions')
    op.drop_table('attendance_submissions')
    op.drop_index(op.f('ix_ussd_sessions_phone_hash'), table_name='ussd_sessions')
    op.drop_table('ussd_sessions')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_teacher_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_sector_id'), table_name='users')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_sector_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_sectors_district_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_ussd_requests_created_at'), table_name='ussd_requests')
    op.drop_table('ussd_requests')
    op.drop_index(op.f('ix_terms_academic_year'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_guardians_phone_e164'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
